# Generated by Django 6.0.5 on 2026-06-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskiqTaskSchedule',
            fields=[
                ('schedule_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('args', models.JSONField(db_default=[], default=list)),
                ('kwargs', models.JSONField(db_default={}, default=dict)),
                ('labels', models.JSONField(db_default={}, default=dict)),
                ('cron', models.CharField(blank=True, max_length=255, null=True)),
                ('cron_offset', models.CharField(blank=True, max_length=64, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('interval', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task schedule',
                'verbose_name_plural': 'Task schedules',
                'db_table': 'taskiq_schedules',
            },
        ),
    ]
